# ===============
# Configuration
# ===============

# Page name
name: Mau-DVMT
# Description of the page/course
description: Samlingsplats för öppet kursmaterial på Malmö Högskola från datavetenskap
# Github repository hosting this page/course
github: https://github.com/mah-dv/mah-dv.github.io
# Google analytics
analytics: xxx
# ex. GitHub pages URL
url: http://mah-dv.github.io/

# Disqus URL
# disqus: 

# Already set as defaults in jekyll > 2.4.x
# highlighter: pygments
# markdown: kramdown
# include: ['.htaccess']

kramdown:
    input: GFM

# Default layouts for posts and pages
defaults:
  -
    scope: 
      path: "courses"
    values:
      layout: "course"
# SASS partial directory and output parameters
sass:
  sass_dir: _sass
  style: :compressed
# Files to be excluded (feel free to exclude files like: search.json, rss.xml, humans.txt, etc.)
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'LICENSE.txt', 'node_modules']
# Encoding
encoding: utf-8
# Main navigation (also found in the footer)
navigation:
    - label: Hem
      href: /
      title: Gå till startsidan
    - label: Kurser
      href: /courses
      title: Gå till kursöversikt
    - label: Kontakt
      href: /contact
      title: Gå till kontaktsidan
